//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DcsDataImporter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pathKneeboardBuilder {
            get {
                return ((string)(this["pathKneeboardBuilder"]));
            }
            set {
                this["pathKneeboardBuilder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pathAto {
            get {
                return ((string)(this["pathAto"]));
            }
            set {
                this["pathAto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevMsnNr {
            get {
                return ((string)(this["prevMsnNr"]));
            }
            set {
                this["prevMsnNr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool standardTraining {
            get {
                return ((bool)(this["standardTraining"]));
            }
            set {
                this["standardTraining"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frequencyPresetFilename {
            get {
                return ((string)(this["frequencyPresetFilename"]));
            }
            set {
                this["frequencyPresetFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string frequencyPresetSafeFilename {
            get {
                return ((string)(this["frequencyPresetSafeFilename"]));
            }
            set {
                this["frequencyPresetSafeFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtCallsign {
            get {
                return ((string)(this["prevTxtCallsign"]));
            }
            set {
                this["prevTxtCallsign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtNrOfAc {
            get {
                return ((string)(this["prevTxtNrOfAc"]));
            }
            set {
                this["prevTxtNrOfAc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtMsnNr {
            get {
                return ((string)(this["prevTxtMsnNr"]));
            }
            set {
                this["prevTxtMsnNr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTasking {
            get {
                return ((string)(this["prevTxtTasking"]));
            }
            set {
                this["prevTxtTasking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtLocation {
            get {
                return ((string)(this["prevTxtLocation"]));
            }
            set {
                this["prevTxtLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevCmbAirbaseDep {
            get {
                return ((string)(this["prevCmbAirbaseDep"]));
            }
            set {
                this["prevCmbAirbaseDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTakeoffTime {
            get {
                return ((string)(this["prevTxtTakeoffTime"]));
            }
            set {
                this["prevTxtTakeoffTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtParking {
            get {
                return ((string)(this["prevTxtParking"]));
            }
            set {
                this["prevTxtParking"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevChkAwacs {
            get {
                return ((string)(this["prevChkAwacs"]));
            }
            set {
                this["prevChkAwacs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsCallsign {
            get {
                return ((string)(this["prevTxtAwacsCallsign"]));
            }
            set {
                this["prevTxtAwacsCallsign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsFreq {
            get {
                return ((string)(this["prevTxtAwacsFreq"]));
            }
            set {
                this["prevTxtAwacsFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsChannel {
            get {
                return ((string)(this["prevTxtAwacsChannel"]));
            }
            set {
                this["prevTxtAwacsChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsPreset {
            get {
                return ((string)(this["prevTxtAwacsPreset"]));
            }
            set {
                this["prevTxtAwacsPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsCp {
            get {
                return ((string)(this["prevTxtAwacsCp"]));
            }
            set {
                this["prevTxtAwacsCp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsBackupFreq {
            get {
                return ((string)(this["prevTxtAwacsBackupFreq"]));
            }
            set {
                this["prevTxtAwacsBackupFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsBackupChannel {
            get {
                return ((string)(this["prevTxtAwacsBackupChannel"]));
            }
            set {
                this["prevTxtAwacsBackupChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsBackupPreset {
            get {
                return ((string)(this["prevTxtAwacsBackupPreset"]));
            }
            set {
                this["prevTxtAwacsBackupPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevChkTacp {
            get {
                return ((string)(this["prevChkTacp"]));
            }
            set {
                this["prevChkTacp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpCallsign {
            get {
                return ((string)(this["prevTxtTacpCallsign"]));
            }
            set {
                this["prevTxtTacpCallsign"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpFreq {
            get {
                return ((string)(this["prevTxtTacpFreq"]));
            }
            set {
                this["prevTxtTacpFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpChannel {
            get {
                return ((string)(this["prevTxtTacpChannel"]));
            }
            set {
                this["prevTxtTacpChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpPreset {
            get {
                return ((string)(this["prevTxtTacpPreset"]));
            }
            set {
                this["prevTxtTacpPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpCp {
            get {
                return ((string)(this["prevTxtTacpCp"]));
            }
            set {
                this["prevTxtTacpCp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpBackupFreq {
            get {
                return ((string)(this["prevTxtTacpBackupFreq"]));
            }
            set {
                this["prevTxtTacpBackupFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpBackupChannel {
            get {
                return ((string)(this["prevTxtTacpBackupChannel"]));
            }
            set {
                this["prevTxtTacpBackupChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpBackupPreset {
            get {
                return ((string)(this["prevTxtTacpBackupPreset"]));
            }
            set {
                this["prevTxtTacpBackupPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtIfrnFreq {
            get {
                return ((string)(this["prevTxtIfrnFreq"]));
            }
            set {
                this["prevTxtIfrnFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtIfrnChannel {
            get {
                return ((string)(this["prevTxtIfrnChannel"]));
            }
            set {
                this["prevTxtIfrnChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtIfrnPreset {
            get {
                return ((string)(this["prevTxtIfrnPreset"]));
            }
            set {
                this["prevTxtIfrnPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAmp {
            get {
                return ((string)(this["prevTxtAmp"]));
            }
            set {
                this["prevTxtAmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtCardinal {
            get {
                return ((string)(this["prevTxtCardinal"]));
            }
            set {
                this["prevTxtCardinal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtLoadout {
            get {
                return ((string)(this["prevTxtLoadout"]));
            }
            set {
                this["prevTxtLoadout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevChkDefault {
            get {
                return ((string)(this["prevChkDefault"]));
            }
            set {
                this["prevChkDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsChallenge {
            get {
                return ((string)(this["prevTxtAwacsChallenge"]));
            }
            set {
                this["prevTxtAwacsChallenge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtAwacsResponse {
            get {
                return ((string)(this["prevTxtAwacsResponse"]));
            }
            set {
                this["prevTxtAwacsResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpChallenge {
            get {
                return ((string)(this["prevTxtTacpChallenge"]));
            }
            set {
                this["prevTxtTacpChallenge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpResponse {
            get {
                return ((string)(this["prevTxtTacpResponse"]));
            }
            set {
                this["prevTxtTacpResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpAbortChallenge {
            get {
                return ((string)(this["prevTxtTacpAbortChallenge"]));
            }
            set {
                this["prevTxtTacpAbortChallenge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTacpAbortResponse {
            get {
                return ((string)(this["prevTxtTacpAbortResponse"]));
            }
            set {
                this["prevTxtTacpAbortResponse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtInternalFreq {
            get {
                return ((string)(this["prevTxtInternalFreq"]));
            }
            set {
                this["prevTxtInternalFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtInternalChannel {
            get {
                return ((string)(this["prevTxtInternalChannel"]));
            }
            set {
                this["prevTxtInternalChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtInternalPreset {
            get {
                return ((string)(this["prevTxtInternalPreset"]));
            }
            set {
                this["prevTxtInternalPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtInternalBackupFreq {
            get {
                return ((string)(this["prevTxtInternalBackupFreq"]));
            }
            set {
                this["prevTxtInternalBackupFreq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtInternalBackupChannel {
            get {
                return ((string)(this["prevTxtInternalBackupChannel"]));
            }
            set {
                this["prevTxtInternalBackupChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtInternalBackupPreset {
            get {
                return ((string)(this["prevTxtInternalBackupPreset"]));
            }
            set {
                this["prevTxtInternalBackupPreset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtMetar {
            get {
                return ((string)(this["prevTxtMetar"]));
            }
            set {
                this["prevTxtMetar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtJoker {
            get {
                return ((string)(this["prevTxtJoker"]));
            }
            set {
                this["prevTxtJoker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtBingo {
            get {
                return ((string)(this["prevTxtBingo"]));
            }
            set {
                this["prevTxtBingo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevChkTma {
            get {
                return ((string)(this["prevChkTma"]));
            }
            set {
                this["prevChkTma"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtTmaEnabled {
            get {
                return ((string)(this["prevTxtTmaEnabled"]));
            }
            set {
                this["prevTxtTmaEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevCmbAirbaseArr {
            get {
                return ((string)(this["prevCmbAirbaseArr"]));
            }
            set {
                this["prevCmbAirbaseArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevCmbAirbaseAlt {
            get {
                return ((string)(this["prevCmbAirbaseAlt"]));
            }
            set {
                this["prevCmbAirbaseAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTcnDep {
            get {
                return ((string)(this["prevColTcnDep"]));
            }
            set {
                this["prevColTcnDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColIlsDep {
            get {
                return ((string)(this["prevColIlsDep"]));
            }
            set {
                this["prevColIlsDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColGndFreqDep {
            get {
                return ((string)(this["prevColGndFreqDep"]));
            }
            set {
                this["prevColGndFreqDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTwrFreqDep {
            get {
                return ((string)(this["prevColTwrFreqDep"]));
            }
            set {
                this["prevColTwrFreqDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTmaFreqDep {
            get {
                return ((string)(this["prevColTmaFreqDep"]));
            }
            set {
                this["prevColTmaFreqDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTcnArr {
            get {
                return ((string)(this["prevColTcnArr"]));
            }
            set {
                this["prevColTcnArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColIlsArr {
            get {
                return ((string)(this["prevColIlsArr"]));
            }
            set {
                this["prevColIlsArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColGndFreqArr {
            get {
                return ((string)(this["prevColGndFreqArr"]));
            }
            set {
                this["prevColGndFreqArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTwrFreqArr {
            get {
                return ((string)(this["prevColTwrFreqArr"]));
            }
            set {
                this["prevColTwrFreqArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTmaFreqArr {
            get {
                return ((string)(this["prevColTmaFreqArr"]));
            }
            set {
                this["prevColTmaFreqArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTcnAlt {
            get {
                return ((string)(this["prevColTcnAlt"]));
            }
            set {
                this["prevColTcnAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColIlsAlt {
            get {
                return ((string)(this["prevColIlsAlt"]));
            }
            set {
                this["prevColIlsAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColGndFreqAlt {
            get {
                return ((string)(this["prevColGndFreqAlt"]));
            }
            set {
                this["prevColGndFreqAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTwrFreqAlt {
            get {
                return ((string)(this["prevColTwrFreqAlt"]));
            }
            set {
                this["prevColTwrFreqAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTmaFreqAlt {
            get {
                return ((string)(this["prevColTmaFreqAlt"]));
            }
            set {
                this["prevColTmaFreqAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColAirbaseDep {
            get {
                return ((string)(this["prevColAirbaseDep"]));
            }
            set {
                this["prevColAirbaseDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColAirbaseArr {
            get {
                return ((string)(this["prevColAirbaseArr"]));
            }
            set {
                this["prevColAirbaseArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColAirbaseAlt {
            get {
                return ((string)(this["prevColAirbaseAlt"]));
            }
            set {
                this["prevColAirbaseAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColElevDep {
            get {
                return ((string)(this["prevColElevDep"]));
            }
            set {
                this["prevColElevDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColElevArr {
            get {
                return ((string)(this["prevColElevArr"]));
            }
            set {
                this["prevColElevArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColElevAlt {
            get {
                return ((string)(this["prevColElevAlt"]));
            }
            set {
                this["prevColElevAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColRwyDep {
            get {
                return ((string)(this["prevColRwyDep"]));
            }
            set {
                this["prevColRwyDep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColRwyArr {
            get {
                return ((string)(this["prevColRwyArr"]));
            }
            set {
                this["prevColRwyArr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColRwyAlt {
            get {
                return ((string)(this["prevColRwyAlt"]));
            }
            set {
                this["prevColRwyAlt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevTxtLandingTime {
            get {
                return ((string)(this["prevTxtLandingTime"]));
            }
            set {
                this["prevTxtLandingTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTypeAwacsAGSupport {
            get {
                return ((string)(this["prevColTypeAwacsAGSupport"]));
            }
            set {
                this["prevColTypeAwacsAGSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColCallsignAwacsAGSupport {
            get {
                return ((string)(this["prevColCallsignAwacsAGSupport"]));
            }
            set {
                this["prevColCallsignAwacsAGSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColFreqAwacsAGSupport {
            get {
                return ((string)(this["prevColFreqAwacsAGSupport"]));
            }
            set {
                this["prevColFreqAwacsAGSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColChannelAwacsAGSupport {
            get {
                return ((string)(this["prevColChannelAwacsAGSupport"]));
            }
            set {
                this["prevColChannelAwacsAGSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColPresetAwacsAGSupport {
            get {
                return ((string)(this["prevColPresetAwacsAGSupport"]));
            }
            set {
                this["prevColPresetAwacsAGSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColBackupAwacsAGSupport {
            get {
                return ((string)(this["prevColBackupAwacsAGSupport"]));
            }
            set {
                this["prevColBackupAwacsAGSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColNotesAwacsAGSupport {
            get {
                return ((string)(this["prevColNotesAwacsAGSupport"]));
            }
            set {
                this["prevColNotesAwacsAGSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTypeAwacsAASupport {
            get {
                return ((string)(this["prevColTypeAwacsAASupport"]));
            }
            set {
                this["prevColTypeAwacsAASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColCallsignAwacsAASupport {
            get {
                return ((string)(this["prevColCallsignAwacsAASupport"]));
            }
            set {
                this["prevColCallsignAwacsAASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColFreqAwacsAASupport {
            get {
                return ((string)(this["prevColFreqAwacsAASupport"]));
            }
            set {
                this["prevColFreqAwacsAASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColChannelAwacsAASupport {
            get {
                return ((string)(this["prevColChannelAwacsAASupport"]));
            }
            set {
                this["prevColChannelAwacsAASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColPresetAwacsAASupport {
            get {
                return ((string)(this["prevColPresetAwacsAASupport"]));
            }
            set {
                this["prevColPresetAwacsAASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColBackupAwacsAASupport {
            get {
                return ((string)(this["prevColBackupAwacsAASupport"]));
            }
            set {
                this["prevColBackupAwacsAASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColNotesAwacsAASupport {
            get {
                return ((string)(this["prevColNotesAwacsAASupport"]));
            }
            set {
                this["prevColNotesAwacsAASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTypeFACASupport {
            get {
                return ((string)(this["prevColTypeFACASupport"]));
            }
            set {
                this["prevColTypeFACASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColCallsignFACASupport {
            get {
                return ((string)(this["prevColCallsignFACASupport"]));
            }
            set {
                this["prevColCallsignFACASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColFreqFACASupport {
            get {
                return ((string)(this["prevColFreqFACASupport"]));
            }
            set {
                this["prevColFreqFACASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColChannelFACASupport {
            get {
                return ((string)(this["prevColChannelFACASupport"]));
            }
            set {
                this["prevColChannelFACASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColPresetFACASupport {
            get {
                return ((string)(this["prevColPresetFACASupport"]));
            }
            set {
                this["prevColPresetFACASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColBackupFACASupport {
            get {
                return ((string)(this["prevColBackupFACASupport"]));
            }
            set {
                this["prevColBackupFACASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColNotesFACASupport {
            get {
                return ((string)(this["prevColNotesFACASupport"]));
            }
            set {
                this["prevColNotesFACASupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTypeTanker1Support {
            get {
                return ((string)(this["prevColTypeTanker1Support"]));
            }
            set {
                this["prevColTypeTanker1Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColCallsignTanker1Support {
            get {
                return ((string)(this["prevColCallsignTanker1Support"]));
            }
            set {
                this["prevColCallsignTanker1Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColFreqTanker1Support {
            get {
                return ((string)(this["prevColFreqTanker1Support"]));
            }
            set {
                this["prevColFreqTanker1Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColChannelTanker1Support {
            get {
                return ((string)(this["prevColChannelTanker1Support"]));
            }
            set {
                this["prevColChannelTanker1Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColPresetTanker1Support {
            get {
                return ((string)(this["prevColPresetTanker1Support"]));
            }
            set {
                this["prevColPresetTanker1Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColBackupTanker1Support {
            get {
                return ((string)(this["prevColBackupTanker1Support"]));
            }
            set {
                this["prevColBackupTanker1Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColNotesTanker1Support {
            get {
                return ((string)(this["prevColNotesTanker1Support"]));
            }
            set {
                this["prevColNotesTanker1Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTypeTanker2Support {
            get {
                return ((string)(this["prevColTypeTanker2Support"]));
            }
            set {
                this["prevColTypeTanker2Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColCallsignTanker2Support {
            get {
                return ((string)(this["prevColCallsignTanker2Support"]));
            }
            set {
                this["prevColCallsignTanker2Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColFreqTanker2Support {
            get {
                return ((string)(this["prevColFreqTanker2Support"]));
            }
            set {
                this["prevColFreqTanker2Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColChannelTanker2Support {
            get {
                return ((string)(this["prevColChannelTanker2Support"]));
            }
            set {
                this["prevColChannelTanker2Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColPresetTanker2Support {
            get {
                return ((string)(this["prevColPresetTanker2Support"]));
            }
            set {
                this["prevColPresetTanker2Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColBackupTanker2Support {
            get {
                return ((string)(this["prevColBackupTanker2Support"]));
            }
            set {
                this["prevColBackupTanker2Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColNotesTanker2Support {
            get {
                return ((string)(this["prevColNotesTanker2Support"]));
            }
            set {
                this["prevColNotesTanker2Support"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColTypeJSTARSupport {
            get {
                return ((string)(this["prevColTypeJSTARSupport"]));
            }
            set {
                this["prevColTypeJSTARSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColCallsignJSTARSupport {
            get {
                return ((string)(this["prevColCallsignJSTARSupport"]));
            }
            set {
                this["prevColCallsignJSTARSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColFreqJSTARSupport {
            get {
                return ((string)(this["prevColFreqJSTARSupport"]));
            }
            set {
                this["prevColFreqJSTARSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColChannelJSTARSupport {
            get {
                return ((string)(this["prevColChannelJSTARSupport"]));
            }
            set {
                this["prevColChannelJSTARSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColPresetJSTARSupport {
            get {
                return ((string)(this["prevColPresetJSTARSupport"]));
            }
            set {
                this["prevColPresetJSTARSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColBackupJSTARSupport {
            get {
                return ((string)(this["prevColBackupJSTARSupport"]));
            }
            set {
                this["prevColBackupJSTARSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string prevColNotesJSTARSupport {
            get {
                return ((string)(this["prevColNotesJSTARSupport"]));
            }
            set {
                this["prevColNotesJSTARSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string pathDocmFile {
            get {
                return ((string)(this["pathDocmFile"]));
            }
            set {
                this["pathDocmFile"] = value;
            }
        }
    }
}
